- hosts: Backend-server
  user: ansible
  become: yes
  connection: ssh


  tasks:
#  - name: Update
 #   become: true
    #shell:  sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm


  - name: Update
    become: true
    shell: sudo yum update -y

  - name: Install mysql
    yum:
      name: mysql-devel
      state: present



  - name: Install mysql
    yum:
      name: mysql
      state: present

#  - name: Update
 #   become: true
  #  shell: sudo yum install -y https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm

 
 # - name: Update
  #  become: true
   # shell: sudo yum install -y mysql-community-client



#  - name: Install mysql-client
 #   yum:
  #    name: mysql-client
   #   state: present
  - name: Update gcc
    yum:
      name: gcc-c++
      state: present

  - name: Install git
    yum:
      name: git
      state: present

  
  - name: Clone a private repository into /home/ansible
    git:
      repo: https://github.com/sandeepraj786/chatapp.git
      clone: yes
      version: master
      dest: /new_chatapp

  - name: Install python 3
    yum:
      name: python3
      state: present

  - name: Install lib
    yum:
      name: python3-devel
      state: present


  - name: Install pip3
    yum:
      name: python3-pip
      
      update_cache: yes
      state: present

  - name: install python3-setuptools
    yum:
       name: python3-setuptools
       state: present

  - name: Install specified python requirements
    pip:
      executable: pip3.7
      requirements: /new_chatapp/requirements.txt
      state: present


  - name: Copy files to a remote machine
    copy:
      src: /home/ansible/django.service
      dest: /etc/systemd/system/

  - name: Execute a command for django shell module
    become: true
    shell: sudo systemctl start django

  - name: Execute a command for django shell module
    become: true
    shell: sudo systemctl enable django
